name: dart_backend_tech_test
description: Starter project for Dart backend technical assessment.
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2
  http_parser: ^4.0.2
  logging: ^1.2.0
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.24.9
  lints: ^3.0.0
